import Image from 'next/image';
import './globals.css';
import { Poppins } from 'next/font/google';
import logo from '../public/logo-05.png';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['900', '200', '300', '400', '500', '600', '700', '800'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <header className="flex justify-between p-4 text-center align-middle h-24 shadow-md my-auto sticky top-0 bg-white px-8 w-full">
          <div className="text-yellow-500 font-semibold text-6xl my-auto">
            <Image src={logo} alt="logo" width={250} height={250} />
          </div>
          <div className="bg-flybondi-yellow rounded-3xl py-2 px-6 text-black font-semibold  my-auto text-xl">
            Carrito
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
